🐈 Add conditional to stop if non captures

diff --git a/src/demo_workflow b/src/demo_workflow
--- a/src/demo_workflow
+++ b/src/demo_workflow
@@ -63,9 +63,17 @@ errors_directory=${files_path}/errores
 # Convierte archivo de morfometría_gatos de xslx a csv
 	echo "CONVIERTE ARCHIVO DE MORFOMETRIA DE XLSX A CSV"
 	source ./src/clean_position_morphometry.sh 
-    clean_morphometry ${cat_morphometry_file_name_xlsx} \
-	&& cambia_formato_fecha ${cat_morphometry_data_file}.csv \
+    clean_morphometry ${cat_morphometry_file_name_xlsx} 
+	row_number=$(wc -l < ${cat_morphometry_data_file}.csv)
+	if [ $row_number -gt 1 ];
+	then
+	cambia_formato_fecha ${cat_morphometry_data_file}.csv \
 		> ${cat_morphometry_data_file}_ISO8601.csv
+	else 
+	echo "NO HAY CAPTURAS"
+	echo "🧐 El resultado de esta verificación los podemos ver a detalle en la carpeta \`errores\` que se genera dentro de nuestra carpeta de datos 🗃️"
+	exit $?
+	fi
 
 # Tiene que ser la salida de la funcion cambia formato_fecha (ISO8601)
 	echo "SELECCIONA CAPTURAS DEL ARCHIVO MORFOMETRÍA GATOS"
